/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c0c7d4",
        "surface-tint": "#a2c9ff",
        "surface-bright": "#353940",
        "secondary-fixed-dim": "#67df70",
        "on-tertiary": "#422c00",
        "on-secondary-fixed-variant": "#005317",
        "on-secondary-fixed": "#002105",
        "on-primary-fixed": "#001c38",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#a2c9ff",
        "on-tertiary-fixed": "#271900",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface": "#10141a",
        "primary-container": "#58a6ff",
        "on-primary": "#00315c",
        "inverse-on-surface": "#2d3137",
        "primary-fixed": "#d3e4ff",
        "outline": "#8b919d",
        "on-tertiary-fixed-variant": "#5f4100",
        "surface-container-high": "#262a31",
        "on-tertiary-container": "#4d3500",
        "surface-container-low": "#181c22",
        "secondary-container": "#27a640",
        "secondary-fixed": "#83fc89",
        "on-primary-container": "#003a6b",
        "error": "#ffb4ab",
        "tertiary-fixed-dim": "#fabc45",
        "surface-variant": "#31353c",
        "surface-dim": "#10141a",
        "background": "#10141a",
        "primary": "#a2c9ff",
        "surface-container-lowest": "#0a0e14",
        "secondary": "#67df70",
        "outline-variant": "#414752",
        "on-secondary": "#00390d",
        "on-background": "#dfe2eb",
        "on-secondary-container": "#00320a",
        "on-primary-fixed-variant": "#004882",
        "inverse-surface": "#dfe2eb",
        "surface-container": "#1c2026",
        "inverse-primary": "#0060aa",
        "on-surface": "#dfe2eb",
        "surface-container-highest": "#31353c",
        "tertiary": "#fabc45",
        "tertiary-fixed": "#ffdeaa",
        "tertiary-container": "#d29922",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
}
