{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runwatch.secretName" . }}
  labels:
    {{- include "runwatch.labels" . | nindent 4 }}
type: Opaque
stringData:
  mongodb-uri: {{ required "mongodb.uri is required" .Values.mongodb.uri | quote }}
  github-webhook-secret: {{ .Values.github.webhookSecret | quote }}
  github-app-id: {{ .Values.github.appId | quote }}
  github-app-private-key: {{ .Values.github.appPrivateKey | quote }}
  admin-api-token: {{ required "adminApiToken is required" .Values.adminApiToken | quote }}
{{- end }}
